### ISSUE TITLE
Undefined index: givenname

### ISSUE THREAD

**Issue by freefcw** [nesl247/laravel-ldap#2]
file: nesl247/laravel-ldap/src/nesl247/LaravelLdap/Ldap.php

```php
                'givenname' => 'last_name',
            ];
        }
 
        $attributes = [];
 
        foreach ($mappings as $ldap => $db) {
            $attributes[$db] = $user[$ldap];
        }
```

It's seems some ldap did not have

**Comment by nesl247** [comment]
This is still in early development, I simply forgot to tag it as 1.0-alpha, not 1.0. It's primary purpose if for my internal use. It's going to be a while before this is probably usable.

**Comment by freefcw** [comment]
Yeah, But I recommend it configurable :)

thanks for your work

**Comment by nesl247** [comment]
Closing this as I have updated the status of the project to mention that it is unmaintained, and not in a finished state. If someone wants to fork it, or for me to transfer the repository to them, they can have it.
