### ISSUE TITLE
Undefined index: ssl

### ISSUE THREAD

**Issue by freefcw** [nesl247/laravel-ldap#3]
file: vendor/nesl247/laravel-ldap/src/nesl247/LaravelLdap/LdapManager.php

```php
    protected function connection()
    {
        if (is_null($this->connection)) {
            $config = $this->getConfig();
 
            $this->connection = new Connection($config['hosts'], $config['username'], $config['password'], $config['ssl']);
        }
 
```

I found the key name in config file is marked as use_ssl

**Comment by nesl247** [comment]
Closing this as I have updated the status of the project to mention that it is unmaintained, and not in a finished state.
